#!/bin/bash

# 1Password Environments Setup Script
# Create environment-specific secret configurations

echo "🌍 1Password Environments Setup"
echo "==============================="

# Check prerequisites
if ! command -v op &> /dev/null; then
    echo "❌ 1Password CLI not found"
    exit 1
fi

echo "✅ 1Password CLI found: $(op --version)"

# Create environment-specific .env files
create_env_file() {
    local env=$1
    local vault=$2
    local filename=".env.$env"
    local upper_env=$(echo $env | tr '[:lower:]' '[:upper:]')

    echo -e "\n📝 Creating $filename for $env environment..."

    cat > "$filename" << EOF
# $env Environment Configuration
# Generated by 1Password CLI - DO NOT EDIT MANUALLY

# Database Configuration
DATABASE_URL=op://$vault/POSTGRESQL_${upper_env}_DATABASE/password
DB_PASSWORD=op://$vault/TEMPORAL_DB_PASSWORD/password

# API Keys
SUPABASE_ANON_KEY=op://$vault/SUPABASE_ANON_KEY/password
SUPABASE_SERVICE_KEY=op://$vault/SUPABASE_SERVICE_ROLE_KEY/credential
FIREWORKS_API_KEY=op://$vault/FIREWORKS_API_KEY/password
FIRECRAWL_API_KEY=op://$vault/FIRECRAWL_API_KEY/password
HUGGINGFACE_API_KEY=op://$vault/HUGGINGFACE_API_KEY/password
OPENROUTER_API_KEY=op://$vault/OPENROUTER_API_KEY/password
KAGI_API_KEY=op://$vault/KAGI_API_KEY/password
TOGETHER_API_KEY=op://$vault/TOGETHER_API_KEY/password
XAI_API_KEY=op://$vault/XAI_API_KEY/password
OLLAMA_API_KEY=op://$vault/OLLAMA_API_KEY/password
POSTHOG_API_KEY=op://$vault/POSTHOG_API_KEY/password
VERCEL_TOKEN=op://$vault/VERCEL_TOKEN/password
SENTRY_AUTH_TOKEN=op://$vault/SENTRY_AUTH_TOKEN/password

# Cloud Platform Tokens
GITHUB_PAT_API_KEY=op://$vault/GITHUB_PAT_API_KEY/token
CLOUDFLARE_API_TOKEN=op://$vault/CLOUDFLARE_API_TOKEN/password

# Environment Variables
NODE_ENV=$env
APP_ENV=$env
LOG_LEVEL=info
EOF

    echo "✅ Created $filename"
}

# Create environment files for different stages
create_env_file "development" "Development"
create_env_file "staging" "Development"  # Using Development vault for staging
create_env_file "production" "Production"

# Create a comprehensive development environment
cat > ".env.development.local" << 'EOF'
# Development Local Overrides
# These override .env.development for local development

# Enable development features
DEBUG=true
LOG_LEVEL=debug

# Development database (local)
# DATABASE_URL=postgresql://localhost:5432/dev_db

# Development API endpoints
# SUPABASE_URL=http://localhost:54321
EOF

echo -e "\n📚 Environment files created:"
echo "   .env.development      - Development environment"
echo "   .env.staging         - Staging environment"
echo "   .env.production     - Production environment"
echo "   .env.development.local - Local development overrides"

echo -e "\n🚀 Usage examples:"
echo "   # Development"
echo "   op run --env-file=.env.development -- npm run dev"
echo ""
echo "   # Production deployment"
echo "   op run --env-file=.env.production -- ./deploy.sh"
echo ""
echo "   # Testing with staging"
echo "   op run --env-file=.env.staging -- npm test"
echo ""
echo "   # Local development with overrides"
echo "   op run --env-file=.env.development --env-file=.env.development.local -- npm run dev"

echo -e "\n🔒 Security notes:"
echo "   • Never commit .env files to version control"
echo "   • Use different vaults for different environments"
echo "   • Rotate secrets regularly"
echo "   • Use service accounts for CI/CD pipelines"